# Generated by Django 5.1.7 on 2025-08-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='core_image/%Y/%m')),
            ],
        ),
    ]
