# Generated by Django 5.1.7 on 2025-09-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
