# Generated by Django 5.1.7 on 2025-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descricao_contato_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
